# Generated by Django 3.2.9 on 2021-11-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_certificate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
